view:
  CLEAR_COLOR: [0.8, 0.8, 0.9, 0.1]
  WINDOW_DIMENSIONS: [500, 500]
  DRAW_AD_RIG: False
  DRAW_AD_TXTR: True
  DRAW_AD_COLOR: False
  DRAW_AD_MESH_LINES: False
controller:
  keyboard_timestep: 0.0333
scene:
DRAW_FLOOR: True
CHARACTER_OFFSET: [0.0, 0.0, 0.0]
