version: "3.7"

services:
  sketch_server:
    build:
      context: .
      dockerfile: Dockerfile
      target: rig_runtime
    ports:
      - 5010:5000
    volumes:
      - type: volume
        source: dev-demo-sketch-out-animations
        target: /home/model-server/rig/server/flask/videos
      - type: volume
        source: dev-demo-sketch-out-interim-files
        target: /home/model-server/rig/server/flask/uploads # TODO fix path
      - type: volume
        source: dev-demo-sketch-out-consents
        target: /home/model-server/rig/server/flask/consent_given_upload_copies
    environment:
      REACT_APP_API_HOST: http://13.59.214.59:5010
    networks:
      ap-net: {}

  detectron2_server:
    build:
      context: .
      dockerfile: Dockerfile
      target: detectron2_runtime
    networks:
      ap-net:
        aliases:
          - detectron2_server # name of network to other services in docker
    volumes:
      - type: volume
        source: dev-demo-sketch-in-model-store
        target: /home/model-server/model_store

  alphapose_server:
    build:
      context: .
      dockerfile: Dockerfile.alphapose
      target: alphapose_runtime
    volumes:
      - type: volume
        source: dev-demo-sketch-in-model-store
        target: /home/ap-server/model_store
    networks:
      ap-net:
        aliases:
          - alphapose_server # name of network to other services in docker

  animation_server:
    build:
      context: .
      dockerfile: Dockerfile.animation
      target: animation_runtime
    # command: /home/animation-server/animate/flask/run.sh
    volumes:
      - type: volume
        source: dev-demo-sketch-out-animations
        target: /home/animation-server/animate/flask/videos
      - type: volume
        source: dev-demo-sketch-out-interim-files
        target: /home/animation-server/animate/flask/uploads
    networks:
      ap-net:
        aliases:
          - animation_server

# Network created by default between services
networks:
  ap-net:
volumes:
  dev-demo-sketch-out-animations:
    external: true
  dev-demo-sketch-out-consents:
    external: true
  dev-demo-sketch-out-interim-files:
    external: true
  dev-demo-sketch-in-model-store:
    external: true
