version: "3.7"

services:
  sketch_server:
    build:
      context: .
      dockerfile: Dockerfile.sketch_api
      target: rig_runtime
      args:
        - BUILD_CONFIG=${BUILD_CONFIG}
    ports:
      - 5000:5000
    volumes:
      - type: bind
        source: ./rig
        target: /home/model-server/rig
      - type: bind
        source: ./tmp/video
        target: /home/model-server/rig/server/flask/videos
      - type: bind
        source: ./tmp/uploads
        target: /home/model-server/rig/server/flask/uploads # TODO fix path
      - type: bind
        source: ./tmp/consents
        target: /home/model-server/rig/server/flask/consents
    
    environment:
      - DETECTRON2_ENDPOINT=${DETECTRON2_ENDPOINT}
      - ALPHAPOSE_ENDPOINT=${ALPHAPOSE_ENDPOINT}
      - ANIMATION_ENDPOINT=${ANIMATION_ENDPOINT}
      - ENABLE_UPLOAD=1
    networks:
      ap-net: {}

  detectron2_server:
    build:
      context: .
      dockerfile: Dockerfile.detectron_runtime
      target: detectron2_runtime
    ports:
      - 5911:5911
      - 8081:8081
      - 8082:8082
    networks:
      ap-net:
        aliases:
          - detectron2_server # name of network to other services in docker
    volumes:
      - type: bind
        source: ./torchserve_d2/model_store
        target: /home/model-server/model_store

  alphapose_server:
    build:
      context: .
      dockerfile: Dockerfile.alphapose
      target: alphapose_runtime
    volumes:
      - type: bind
        source: ./torchserve_ap/model_store
        target: /home/ap-server/model_store
    networks:
      ap-net:
        aliases:
          - alphapose_server # name of network to other services in docker

  animation_server:
    build:
      context: .
      dockerfile: Dockerfile.animation
      target: animation_runtime
      args:
        - BUILD_CONFIG=${BUILD_CONFIG}
        - USER_ID=${USER_ID} \
        - GROUP_ID=${GROUP_ID}
    # command: /home/animation-server/animate/flask/run.sh
    volumes:
      - type: bind
        source: ./animate
        target: /home/animation-server/animate
      - type: bind
        source: ./tmp/video
        target: /home/animation-server/animate/flask/videos # TODO fix path
      - type: bind
        source: ./tmp/uploads
        target: /home/animation-server/animate/flask/uploads # TODO fix path
    networks:
      ap-net:
        aliases:
          - animation_server

# Network created by default between services
networks:
  ap-net:
