version: "3.7"

services:
  sketch_server:
    image: sketch_flask
    build:
      context: .
      dockerfile: Dockerfile

    command: ./run.sh
    ports:
      - 5010:5000
    volumes:
      - type: volume
        source: dev-demo-sketch-out-animations
        target: /home/model-server/rig/server/flask/videos
        #  - type: volume
        # source: dev-demo-sketch-out-consents
        #target: /home/model-server/rig/server/flask/consent_given_upload_copies
    environment:
      REACT_APP_API_HOST: http://13.59.214.59:5010
    networks:
      ap-net: {}

  alphapose_server:
    image: runtime
    build:
      context: .
      dockerfile: Dockerfile.alphapose
    command: ./torchserve_ap/torchserve_start2.sh
    networks:
      ap-net:
        aliases:
          - alphapose_server
# Network created by default between services
networks:
  ap-net:
volumes:
  dev-demo-sketch-out-animations:
    external: true
    #  dev-demo-sketch-out-consents:
    #    driver: rexray/s3fs
