version: "3.7"

services:
  sketch_server:
    image: sketch_flask
    build:
      context: .
      dockerfile: Dockerfile

    command: ./run.sh
    ports:
      - 5000:5000
    volumes:
      - ./videos:/app/out/public/videos
    environment:
      REACT_APP_API_HOST: http://localhost:5000
    networks:
      ap-net: {}

  alphapose_server:
    image: runtime
    build:
      context: .
      dockerfile: Dockerfile.alphapose
    command: ./torchserve_ap/torchserve_start2.sh
    networks:
      ap-net:
        aliases:
          - alphapose_server
# Network created by default between services
networks:
  ap-net:
