version: "3.7"

services:
  sketch_server:
    build:
      context: .
      dockerfile: Dockerfile.sketch_api
      target: rig_runtime
    ports:
      - 5000:5000
    environment:
      - DETECTRON2_ENDPOINT=${DETECTRON2_ENDPOINT}
      - ALPHAPOSE_ENDPOINT=${ALPHAPOSE_ENDPOINT}
      - ANIMATION_ENDPOINT=${ANIMATION_ENDPOINT}
      - AWS_S3_INTERIM_BUCKET=${AWS_S3_INTERIM_BUCKET}
      - AWS_S3_CONSENTS_BUCKET=${AWS_S3_CONSENTS_BUCKET}
      - AWS_S3_VIDEOS_BUCKET=${AWS_S3_VIDEOS_BUCKET}
      - USE_AWS=1
      - ENABLE_UPLOAD=${ENABLE_UPLOAD}
    networks:
      ap-net: {}
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-2
        awslogs-group: dev-demo-sketch-log-group
        awslogs-stream: dev-demo-sketch-www-logs

  detectron2_server:
    build:
      context: .
      dockerfile: Dockerfile.detectron_runtime
      target: detectron2_runtime
    networks:
      ap-net:
        aliases:
          - detectron2_server # name of network to other services in docker
    volumes:
      - type: volume
        source: dev-demo-sketch-in-model-store
        target: /home/model-server/model_store
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-2
        awslogs-group: dev-demo-sketch-log-group
        awslogs-stream: dev-demo-sketch-detectron2-logs

  alphapose_server:
    build:
      context: .
      dockerfile: Dockerfile.alphapose
      target: alphapose_runtime
    volumes:
      - type: volume
        source: dev-demo-sketch-in-model-store
        target: /home/ap-server/model_store
    networks:
      ap-net:
        aliases:
          - alphapose_server # name of network to other services in docker
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-2
        awslogs-group: dev-demo-sketch-log-group
        awslogs-stream: dev-demo-sketch-alphapose-logs

  animation_server:
    build:
      context: .
      dockerfile: Dockerfile.animation
      target: animation_runtime
      args:
        - BUILD_CONFIG=${BUILD_CONFIG}
    environment:
      - AWS_S3_INTERIM_BUCKET=${AWS_S3_INTERIM_BUCKET}
      - AWS_S3_CONSENTS_BUCKET=${AWS_S3_CONSENTS_BUCKET}
      - AWS_S3_VIDEOS_BUCKET=${AWS_S3_VIDEOS_BUCKET}
      - USE_AWS=1
    networks:
      ap-net:
        aliases:
          - animation_server
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-2
        awslogs-group: dev-demo-sketch-log-group
        awslogs-stream: dev-demo-sketch-animation-logs

  www_deploy:
    build:
      context: .
      dockerfile: Dockerfile.www
      args:
        - AWS_S3_WWW_BUCKET=${AWS_S3_WWW_BUCKET}
        - SKETCH_API_ENDPOINT=${SKETCH_API_ENDPOINT}
        - VIDEO_CDN_URL=${VIDEO_CDN_URL}
        - ENABLE_UPLOAD=${ENABLE_UPLOAD}

# Network created by default between services
networks:
  ap-net:
volumes:
  dev-demo-sketch-in-model-store:
    external: true