Cameras:
  - name: Free Cam
    type: free
    cam_pos: [0.5, 0.0, 4.0]
    cam_up:  [0.0, 0.1, 0.0]
    yaw: -90.0

  - name: Triangulation
    type: triangulation
    cam_pos: [0.5, 0.0, 4.0]
    cam_up:  [0.0, 1.0, 0.0]
    yaw: -90.0

  - name: Sketch Cam
    type: sketch
    cam_pos: [0.0, 0.0, 2.5]
    cam_up:  [0.0, 1.0, 0.0]
    yaw: -90.0

  - name: Upper Limb Cam
    type: bvh
    cam_pos: [1.5, 0.0, 0.0]  #[1.5, 0, 0] for front, [0, 0, 2.5] for side
    cam_up:  [0.0, 1.0, 0.0]
    yaw: 180.0  #180 for straight ahead, -90.0 for side
    retarget_bodypart_group: upper_limb_segments  # ignored if camera.type != bvh. One of 'upper_limb_segments', 'lower_limb_segments', or 'trunk_segments'

  - name: Lower Limb Cam
    type: bvh
    cam_pos: [0.0, 0.0, 2.5]  #[1.5, 0, 0] for front, [0, 0, 2.5] for side
    cam_up:  [0.0, 1.0, 0.0]
    yaw: -90.0  #180 for straight ahead, -90.0 for side
    retarget_bodypart_group: lower_limb_segments  # ignored if camera.type != bvh. One of 'upper_limb_segments', 'lower_limb_segments', or 'trunk_segments'

  - name: Trunk Cam
    type: bvh
    cam_pos: [0.0, 0.0, 2.5]  #[1.5, 0, 0] for front, [0, 0, 2.5] for side
    cam_up:  [0.0, 1.0, 0.0]
    yaw: -90.0  #180 for straight ahead, -90.0 for side
    retarget_bodypart_group: trunk_segments  # ignored if camera.type != bvh. One of 'upper_limb_segments', 'lower_limb_segments', or 'trunk_segments'
