# Any parameters specified here will overwrite those in base.yaml
# motion and character_config are mandatory
# Anything else from base.yaml can be copied here and modified

motion: ../Data/BVH/sst/query_4_1.bvh
character_config: ../Data/Texture/nick_cat.yaml
DRAW_FLOOR: True
DRAW_BVH: False
SHOW_ORIGINAL_POSE_ONLY: False
CALCULATE_RENDER_ORDER: True
OUTPUT_PATH: 'output'
RENDER_MODE: RENDER
RENDER_FPS: 18

SHOW_MULTI_CAMERAS: False  # whether to show all windows or not
