motion: ../Data/BVH/mixamo/Jab_Cross_mixamo.com.bvh
character_config: ../Data/Texture/nick_cat.yaml
DRAW_FLOOR: True
DRAW_BVH: False
SHOW_ORIGINAL_POSE_ONLY: False
CALCULATE_RENDER_ORDER: False
RENDER_MODE: INTERACT
RENDER_FPS: 18

# cameras_sss.yaml