motion: ../Data/BVH/mixamo/Climbing_Ladder_mixamo.com.bvh
character_config: ../Data/Texture/nick_cat.yaml
DRAW_FLOOR: True
DRAW_BVH: False
SHOW_ORIGINAL_POSE_ONLY: False
CALCULATE_RENDER_ORDER: False
RENDER_MODE: INTERACT
RENDER_FPS: 18

ROOT_POSITION_UPDATE_TYPE: velocity  # either 'position' or 'velocity'

# ./main.sh mixamo_climb_ladder.yaml cameras_sss.yaml