scene:
  ANIMATED_CHARACTERS:
    - character_cfg: /Users/hjessmith/Desktop/img/char_cfg.yaml
      motion_cfg: /Users/hjessmith/Projects/AnimatedDrawings/animate/config/motion_zombie.yaml
      retarget_cfg: /Users/hjessmith/Projects/AnimatedDrawings/animate/config/retarget.yaml
controller:
  MODE: 'video_render'
  OUTPUT_VIDEO_PATH: /Users/hjessmith/Desktop/output_video.mp4
view:
  USE_MESA: True