bvh_projection_mapping_methods:
  Lower Limbs: pca
  Trunk: frontal
  Upper Limbs: pca
char_starting_location: [0.0, 0.0, 0.0]
char_bodypart_groups:
- depth_drivers:
  - Hips
  joints:
  - right_shoulder
  - left_shoulder
  - right_hip
  - left_hip
  - torso
  - neck
- depth_drivers:
  - LeftHand
  joints:
  - left_elbow
  - left_hand
- depth_drivers:
  - RightHand
  joints:
  - right_elbow
  - right_hand
- depth_drivers:
  - LeftFoot
  joints:
  - left_knee
  - left_foot
- depth_drivers:
  - RightFoot
  joints:
  - right_knee
  - right_foot
char_bvh_root_offset_scaling:
  bvh_projection_bodypart_group_for_offset: Lower Limbs
  bvh_skel:
  - - RightFoot
    - RightLeg
    - RightUpLeg
  - - LeftFoot
    - LeftLeg
    - LeftUpLeg
  character:
  - - left_foot
    - left_knee
    - left_hip
  - - right_foot
    - right_knee
    - right_hip
char_joint_bvh_joints_mapping:
  left_elbow: !!python/tuple
  - LeftArm
  - LeftForeArm
  left_foot: !!python/tuple
  - LeftLeg
  - LeftFoot
  left_hand: !!python/tuple
  - LeftForeArm
  - LeftHand
  left_knee: !!python/tuple
  - LeftUpLeg
  - LeftLeg
  neck: !!python/tuple
  - Hips
  - Neck
  right_elbow: !!python/tuple
  - RightArm
  - RightForeArm
  right_foot: !!python/tuple
  - RightLeg
  - RightFoot
  right_hand: !!python/tuple
  - RightForeArm
  - RightHand
  right_knee: !!python/tuple
  - RightUpLeg
  - RightLeg
