DRAW_FLOOR: True
DRAW_AD_RETARGET_BVH: False
ANIMATED_CHARACTERS:
  - character_cfg: /Users/hjessmith/Desktop/img/char_cfg.yaml
    motion_cfg: /Users/hjessmith/Projects/AnimatedDrawings/animate/config/motion_zombie.yaml
    retarget_cfg: /Users/hjessmith/Projects/AnimatedDrawings/animate/config/retarget.yaml
view:
  CLEAR_COLOR: [0.8, 0.8, 0.9, 0.1]
  WINDOW_DIMENSIONS: [500, 500]
  DRAW_AD_RIG: False
  DRAW_AD_TXTR: True
  DRAW_AD_COLOR: False
  DRAW_AD_MESH_LINES: False
  USE_MESA: False
  CAMERA_POS: [0.0, 0.5, 2.0]
  CAMERA_FWD: [0.0, 0.5, 2.0]
controller:
  KEYBOARD_TIMESTEP: 0.0333
  MODE: 'interactive'
  OUTPUT_VIDEO_PATH: /Users/hjessmith/Desktop/output.mp4
