scene:
  ANIMATED_CHARACTERS:
    - character_cfg: examples/characters/char2/char_cfg.yaml
      motion_cfg: examples/config/motion_dab.yaml
      retarget_cfg: examples/config/retarget.yaml
controller:
  MODE: 'video_render'
  OUTPUT_VIDEO_PATH: output_video/char1_zombie.mp4