MODEL:
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128
    NUM_CLASSES: 1
    SCORE_THRESH_TEST: 0.7
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  IMS_PER_BATCH: 2
  BASE_LR: 0.00025
  MAX_ITER: 3000
DATASETS:
  TRAIN: ("humanoidsketch_train",)
  TEST: ("humanoidsketch_val",)
DATALOADER:
    NUM_WORKERS: 2 
VERSION: 2
